[package]
name = "ulid-python"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pyulid"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.24.0"
rand = "0.9.2"
